const { GoogleGenAI } = require("@google/genai");
const puppeteer = require("puppeteer");

const ai = new GoogleGenAI({
  apiKey: process.env.GOOGLE_GENAI_API_KEY,
});

async function generateInterviewReport({
  jobDescription,
  resume,
  selfDescription,
}) {
  const prompt = `
You are an expert interview coach.

RESUME:
${resume}

SELF DESCRIPTION:
${selfDescription}

JOB DESCRIPTION:
${jobDescription}

You MUST return a valid JSON object with EXACTLY this structure:

{
  "reportTitle": "Short title for this interview report based on the job description (e.g. 'MERN Stack Developer Interview Prep')",
  "matchScore": 75,
  "technicalQuestions": [
    { "question": "...", "intention": "...", "answer": "..." },
    { "question": "...", "intention": "...", "answer": "..." },
    { "question": "...", "intention": "...", "answer": "..." },
    { "question": "...", "intention": "...", "answer": "..." },
    { "question": "...", "intention": "...", "answer": "..." }
  ],
  "behaviourQuestions": [
    { "question": "...", "intention": "...", "answer": "..." },
    { "question": "...", "intention": "...", "answer": "..." },
    { "question": "...", "intention": "...", "answer": "..." },
    { "question": "...", "intention": "...", "answer": "..." }
  ],
  "skillGaps": [
    { "skill": "skill name here", "severity": "low" },
    { "skill": "skill name here", "severity": "medium" },
    { "skill": "skill name here", "severity": "high" }
  ],
  "preparationPlan": [
    { "day": 1, "focus": "focus here", "tasks": ["task 1", "task 2", "task 3"] },
    { "day": 2, "focus": "focus here", "tasks": ["task 1", "task 2", "task 3"] },
    { "day": 3, "focus": "focus here", "tasks": ["task 1", "task 2", "task 3"] },
    { "day": 4, "focus": "focus here", "tasks": ["task 1", "task 2", "task 3"] },
    { "day": 5, "focus": "focus here", "tasks": ["task 1", "task 2", "task 3"] },
    { "day": 6, "focus": "focus here", "tasks": ["task 1", "task 2", "task 3"] },
    { "day": 7, "focus": "focus here", "tasks": ["task 1", "task 2", "task 3"] }
  ]
}

STRICT RULES:
- matchScore must be a number between 0 and 100 representing how well the candidate matches the job
- title must be a short descriptive title for this interview report
- severity must be exactly "low", "medium", or "high"
- Every array must contain objects, never plain strings
- Fill in all "..." with real content based on the candidate's resume and job description
`;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      // ❌ no responseSchema
    },
  });

  const clean = response.text.replace(/```json|```/g, "").trim();
  console.log("AI raw response:", clean);
  return JSON.parse(clean);
}

async function generatePdfFromHtml(htmlContent) {
  const browser = await puppeteer.launch({
    headless: "new",
    args: [
      "--no-sandbox",
      "--disable-setuid-sandbox",
      "--disable-dev-shm-usage",
    ],
  });
  const page = await browser.newPage();
  await page.setContent(htmlContent, { waitUntil: "networkidle0" });

  const pdfBuffer = await page.pdf({
    format: "A4",
    printBackground: true,
    margin: { top: "20mm",
      bottom: "20mm",
      left: "15mm",
      right: "15mm",
    },
  });

  await browser.close();
  return pdfBuffer;
  
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
  const prompt = `
Generate an optimized resume for the candidate based on the following details:

RESUME:
${resume}

SELF DESCRIPTION:
${selfDescription}

JOB DESCRIPTION:
${jobDescription}

You MUST return a valid JSON object with EXACTLY this structure:
{
  "html": "complete HTML content here"
}

STRICT RULES:
- Return ONLY the JSON object, nothing else
- The "html" field must contain complete, valid HTML for a resume
- The resume must be tailored for the given job description
- Highlight the candidate's strengths and relevant experience
- The HTML must be well-formatted, structured, and visually appealing
- Use simple professional colors and font styles
- Do NOT make it sound AI-generated — write like a real human resume
- Must be ATS friendly and easily parsable
- Keep it concise — ideally 1 page, maximum 2 pages when converted to PDF
- Focus on quality over quantity
- Include only relevant information that increases chances of getting an interview call
- Use inline CSS for styling since it will be converted to PDF
- The resume should be optimized to pass through Applicant Tracking Systems (ATS) and catch the recruiter's attention based on the job description provided
- The resume should be tailored for the specific job description, emphasizing the candidate's relevant skills, experience, and achievements that align with the requirements of the job.
- The content should not be sound like it was generated by AI. It should be close as possible to a real human-written resume.
- You can highlight the content using some colors and different font sizes, but keep it professional and suitable for a resume. Avoid using too many colors or overly creative designs since it needs to be ATS friendly. Focus on making it visually appealing but still professional and easy to read.
`;

  const response = await ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
    },
  });

  const clean = response.text.replace(/```json|```/g, "").trim();
  // console.log("AI resume response:", clean);

  const jsonContent = JSON.parse(clean);
  const pdfBuffer = await generatePdfFromHtml(jsonContent.html);
  return pdfBuffer;
}

module.exports = { generateInterviewReport, generateResumePdf };
